//+------------------------------------------------------------------+
//|  SymbolMap.mqh  (MQL5)                                             |
//|  Resolve a canonical instrument name to THIS broker's symbol.      |
//|                                                                    |
//|  github.com/metatraderVPS/metatrader-broker-symbols                |
//|  Data CC BY 4.0 · code MIT                                         |
//|                                                                    |
//|  Why this exists: MetaTrader symbol names are case-sensitive and   |
//|  are never fuzzy-matched, so an EA that hard-codes "XAUUSD" simply |
//|  fails on a broker quoting "XAUUSD.m". Resolution order:           |
//|    1. the canonical name itself                                    |
//|    2. every spelling seen across 241 measured brokers                 |
//|    3. a suffix/prefix scan of the terminal's own symbol list       |
//|  Step 3 means this keeps working on a broker not in the dataset.   |
//+------------------------------------------------------------------+
#property strict

// Returns the first symbol in the array that exists on this terminal.
string PickExisting(string &candidates[])
{
   int n=ArraySize(candidates);
   for(int i=0;i<n;i++)
     {
      string s=candidates[i];
      if(SymbolSelect(s,true)) return(s);
     }
   return("");
}

// Last-resort scan: any Market Watch symbol starting with the canonical
// name, which catches suffix schemes we have never seen.
string ScanTerminal(string canonical)
{
   int total=SymbolsTotal(false);
   for(int i=0;i<total;i++)
     {
      string s=SymbolName(i,false);
      if(StringFind(s,canonical)==0 && SymbolSelect(s,true)) return(s);
     }
   return("");
}

// Main entry point. Returns "" if this broker does not offer the instrument.
string ResolveSymbol(string canonical)
{
   string direct[1]; direct[0]=canonical;
   string hit=PickExisting(direct);
   if(hit!="") return(hit);

   if(canonical=="ASX200") { string a[]={"AUS200","AU200","ASX200","AUS200Cash",".AUS200",".AUS200Cash","[AUS200]-T","AU200U6","AUS200c","AUS200.c","AUS200+","#AUS200","#ASX200","AU200.S","#AU200H_","ASX200.cash","AUS200_SPOT","AUS200p","AU200.E","AUS200_m","AUS200Cash#","AU200x","AUS200spot","AUS200.","AU200=","AU200.mt4",".AUS200.","AU200Cash"}; return(PickExisting(a)); }
   if(canonical=="AUDCAD") { string a[]={"AUDCAD","AUDCAD.","AUDCAD!","AUDCAD-T","AUDCAD.c","AUDCAD.p","AUDCAD.fx","AUDCAD.s","AUDCAD.ecn","AUDCAD.S","AUDCAD.a","AUDCAD...","AUDCAD.P","AUDCADp","AUDCADpro","AUDCAD.esw","AUDCADm","AUDCADf","AUDCAD.e","AUDCAD.raw","AUDCAD+","AUDCAD-","AUDCAD.x","AUDCADx","AUDCAD.iux","AUDCAD.ffx","AUDCAD.MRC","AUDCAD..","AUDCAD_SG","AUDCAD.min","AUDCAD=","AUDCADi","AUDCADv","AUDCAD.z"}; return(PickExisting(a)); }
   if(canonical=="AUDCHF") { string a[]={"AUDCHF","AUDCHF.","AUDCHF!","AUDCHF-T","AUDCHF.p","AUDCHF.fx","AUDCHF.s","AUDCHF.ecn","AUDCHF.S","AUDCHF...","AUDCHF.sb","AUDCHFp","AUDCHF.c","AUDCHFpro","AUDCHF.esw","AUDCHFm","AUDCHFv","AUDCHFf","AUDCHF.e","AUDCHF.raw","AUDCHF+","AUDCHF-","AUDCHF.x","AUDCHFx","AUDCHF.iux","AUDCHF.ffx","AUDCHF.MRC","AUDCHF..","AUDCHF_SG","AUDCHF.min","AUDCHF=","AUDCHFi","AUDCHF.z"}; return(PickExisting(a)); }
   if(canonical=="AUDJPY") { string a[]={"AUDJPY","AUDJPY!","AUDJPY-T","AUDJPY.","AUDJPY.z","AUDJPY.fx","AUDJPY.s","AUDJPY.ecn","AUDJPY.S","AUDJPY.a","AUDJPY...","AUDJPY.sb","AUDJPYp","AUDJPY.c","AUDJPYpro","AUDJPY.esw","AUDJPY#","AUDJPYm","AUDJPYf","AUDJPY.e","AUDJPY.raw","AUDJPY+","AUDJPY-","AUDJPYx","AUDJPY.iux","AUDJPY.ffx","AUDJPY.MRC","AUDJPY..","AUDJPY_SG","AUDJPY.min","AUDJPY=","AUDJPY.sg","AUDJPYMic","AUDJPY.1","AUDJPY.t","AUDJPYi","AUDJPY.p"}; return(PickExisting(a)); }
   if(canonical=="AUDNZD") { string a[]={"AUDNZD","AUDNZD!","AUDNZD.","AUDNZD.s","AUDNZD-T","AUDNZD.p","AUDNZD.fx","AUDNZD.ecn","AUDNZD.S","AUDNZD.vip","AUDNZD...","AUDNZD.sb","AUDNZDp","AUDNZD.c","AUDNZDpro","AUDNZD.esw","AUDNZDm","AUDNZDf","AUDNZD.e","AUDNZD.raw","AUDNZD+","AUDNZD-","AUDNZDx","AUDNZD.iux","AUDNZD.ffx","AUDNZD.MRC","AUDNZD..","AUDNZD_SG","AUDNZD.min","AUDNZD=","AUDNZD.sg","AUDNZDMic","AUDNZD.1","AUDNZD.ct","AUDNZDi","AUDNZD.z"}; return(PickExisting(a)); }
   if(canonical=="AUDSGD") { string a[]={"AUDSGD","AUDSGDv","AUDSGD.p","AUDSGD.","AUDSGD.fx","AUDSGD-T","AUDSGD.a","AUDSGD.sb","AUDSGD.m","AUDSGD.c","AUDSGD#","AUDSGDm","AUDSGD!","AUDSGD.raw","AUDSGD.pro","AUDSGD.x","AUDSGD.iux","AUDSGD.ffx","AUDSGD.ecn","AUDSGD.."}; return(PickExisting(a)); }
   if(canonical=="AUDUSD") { string a[]={"AUDUSD","AUDUSD.p","AUDUSDm","AUDUSD.","AUDUSD.fx","AUDUSD.ecn","AUDUSD-T","AUDUSD...","AUDUSD.sb","AUDUSDpro","AUDUSD.esw","AUDUSDf","AUDUSD.e","AUDUSD.raw","AUDUSD.c","AUDUSD-","AUDUSD.z","AUDUSDx","AUDUSD.iux","AUDUSD.s","AUDUSD.MRC","AUDUSD..","AUDUSD_SG","AUDUSD=","AUDUSD.sg","AUDUSD!","AUDUSD.fix","AUDUSD.1","AUDUSD.t","AUDUSDi","AUDUSDv"}; return(PickExisting(a)); }
   if(canonical=="BCHUSD") { string a[]={"BCHUSD","BCHUSDT","BCHUSD.","BCHUSD-T","BCHUSD-","BCHUSD#","BCHUSDm","#BCHUSD","BCHUSD="}; return(PickExisting(a)); }
   if(canonical=="BRENT") { string a[]={"XBRUSD","BRENT","UKOIL","UKOil","Brent","BRENTCash","UKOIL.c","#BRENT","BRENT-T",".UKOil","XBRUSD.",".XBRUSD","XBRUSD.s","UKOIL.S","#UKOILF_","UKOilSpot","UKOIL.CASH","UKOilp","XBRUSD.c","UK.OIL","$$BRENT","UKOIL.c.","UKOil.m","UKOIL.p","UKOIL.","XBRUSD.g","BRENT.f","BRENT.mt4","XBRUSD.n","UKOIL+","UKOilCash","XBRUSD.z"}; return(PickExisting(a)); }
   if(canonical=="BTCUSD") { string a[]={"BTCUSD","BTCUSDT","BTCUSD.","BTCUSD-T","BTCUSD-","BTCUSDm","BTCUSD`","BTCUSD.futu","BTCUSD="}; return(PickExisting(a)); }
   if(canonical=="CAC40") { string a[]={"FRA40","CAC40","F40","FRA40Cash","[FRA40]-T",".F40","FRA40U6","FRA40c","F40.c","#CAC40","#FRANCE40","FRA40+","FRA.40","Fra40","CAC40.cash","FRA_40",".FRA40","CAC40_SPOT","FRA40p","$F40","FRA.40+","#FRA40_U26","CAC_40","#France40","FRA40.U6","FRA40spot","FRA40.f","FRA40.","FRA40.t",".F40."}; return(PickExisting(a)); }
   if(canonical=="CADCHF") { string a[]={"CADCHF","CADCHF.","CADCHF-T","CADCHFm","CADCHF.fx","CADCHF.s","CADCHF!","CADCHF.S","CADCHF.pro","CADCHF...","CADCHFp","CADCHF.c","CADCHFpro","CADCHFv","CADCHFf","CADCHF.e","CADCHF.raw","CADCHF+","CADCHF-","CADCHF.p","CADCHF-f","CADCHFx","CADCHF.iux","CADCHF.ffx","CADCHF.ecn","CADCHF.MRC","CADCHF..","CADCHF.min","CADCHF=","CADCHFi","CADCHF.z"}; return(PickExisting(a)); }
   if(canonical=="CADJPY") { string a[]={"CADJPY","CADJPY-T","CADJPYm","CADJPY.","CADJPY.fx","CADJPY.s","CADJPY.ecn","CADJPY!","CADJPY.S","CADJPY.pxm","CADJPY...","CADJPY.sb","CADJPYp","CADJPY.c","CADJPYpro","CADJPY.esw","CADJPY#","CADJPYv","CADJPYf","CADJPY.e","CADJPY.raw","CADJPY+","CADJPY-","CADJPYmicro","CADJPYx","CADJPY.iux","CADJPY.ffx","CADJPY.MRC","CADJPY..","CADJPY_SG","CADJPY.min","CADJPY=","CADJPY.n","CADJPYi","CADJPY.z"}; return(PickExisting(a)); }
   if(canonical=="CHFJPY") { string a[]={"CHFJPY","CHFJPY.","CHFJPY!","CHFJPY-T","CHFJPY.c","CHFJPY.p","CHFJPY.fx","CHFJPY.s","CHFJPY.ecn","CHFJPY.S","CHFJPY.pro","CHFJPY...","CHFJPY.sb","CHFJPYp","CHFJPYpro","CHFJPY.esw","CHFJPYm","CHFJPYf","CHFJPY.e","CHFJPY.raw","CHFJPY+","CHFJPY-","CHFJPY.x","CHFJPYx","CHFJPY.iux","CHFJPY.ffx","CHFJPY.MRC","CHFJPY..","CHFJPY_SG","CHFJPY.min","CHFJPY=","CHFJPYMic","CHFJPY.1","CHFJPYi","CHFJPY.z"}; return(PickExisting(a)); }
   if(canonical=="CHFSGD") { string a[]={"CHFSGD","CHFSGD.pro","CHFSGD.p","CHFSGD.fx","CHFSGD-T","CHFSGDp","CHFSGDm","CHFSGDv","CHFSGD!","CHFSGD.raw","CHFSGD.","CHFSGDm#","CHFSGD.ffx","CHFSGD.ecn","CHFSGD.."}; return(PickExisting(a)); }
   if(canonical=="DAX40") { string a[]={"GER40","GER30","DE40","DAX30","DE30",".DE30Cash","DAX","GER40Cash","[GER40]-T",".DE40","DE40U6","GER40c","#DAX30","@DAX_U6","DAX40","#DAX","GER.30","Ger40","DE40.S","#DE30_","DAX30.cash","GER_30","DE40.f",".GER40","GER30_SPOT","GER30p","DE40.E","$DE30","DAX40.f","DE40.c.","DE40.m","DE.30+","GER40_m","#GER40_U26","DAX_30","DAX.p",".DE40Cash","DE30U4","DE30x","DE40.U6","GER30.s","GER30CASH.","GER30spot","GER30m","DE30.f","DAX40U6","DE40U6.","DAX40="}; return(PickExisting(a)); }
   if(canonical=="ETHUSD") { string a[]={"ETHUSD","ETHUSDT","ETHUSD.","ETHUSD-T","ETHUSDm","ETHUSD.futu","ETHUSD=","ETHUSD.c"}; return(PickExisting(a)); }
   if(canonical=="EURAUD") { string a[]={"EURAUD","EURAUD.p","EURAUD.","EURAUD!","EURAUD-T","EURAUD.fx","EURAUD.s","EURAUD.ecn","EURAUD.S","EURAUD...","EURAUD.sb","EURAUDp","EURAUD.c","EURAUDpro","EURAUD.esw","EURAUDm","EURAUDf","EURAUD.e","EURAUD.raw","EURAUD+","EURAUD-","EURAUDx","EURAUD.iux","EURAUD.ffx","EURAUD.MRC","EURAUD..","EURAUD_SG","EURAUD.min","EURAUD=","EURAUD.sg","EURAUDMic","EURAUD.1","EURAUDi","EURAUD.z"}; return(PickExisting(a)); }
   if(canonical=="EURCAD") { string a[]={"EURCAD","EURCAD.","EURCAD-T","EURCAD.fx","EURCAD.s","EURCAD.ecn","EURCAD!","EURCAD.S","EURCAD.vip","EURCAD...","EURCAD.sb","EURCADp","EURCAD.c","EURCADpro","EURCAD.esw","EURCADm","EURCADv","EURCADf","EURCAD.e","EURCAD.raw","EURCAD+","EURCAD-","EURCAD.lp","EURCADx","EURCAD.iux","EURCAD.ffx","EURCAD.MRC","EURCAD..","EURCAD_SG","EURCAD.min","EURCAD=","EURCADMic","EURCAD.1","EURCAD.n","EURCADi","EURCAD.p","EURCAD.z"}; return(PickExisting(a)); }
   if(canonical=="EURCHF") { string a[]={"EURCHF","EURCHF!","EURCHF-T","EURCHFv","EURCHF.","EURCHF.fx","EURCHF.s","EURCHF.ecn","EURCHF.S","EURCHF...","EURCHF.sb","EURCHFp","EURCHF.c","EURCHFpro","EURCHF.esw","EURCHF#","EURCHFm","EURCHFf","EURCHF.e","EURCHF.raw","EURCHF-","EURCHF.p","EURCHF.lp","EURCHFx","EURCHF.iux","EURCHF.ffx","EURCHF.MRC","EURCHF..","EURCHF_SG","EURCHF.min","EURCHF=","EURCHF.sg","EURCHF.1","EURCHF.t","EURCHFi","EURCHF.z"}; return(PickExisting(a)); }
   if(canonical=="EURCZK") { string a[]={"EURCZK","EURCZK-T","EURCZK.fx","EURCZK.pxm","EURCZK...","EURCZK-","EURCZKm","EURCZK.raw","EURCZK+","EURCZK.ffx","EURCZK.min","EURCZK!","EURCZK.p"}; return(PickExisting(a)); }
   if(canonical=="EURDKK") { string a[]={"EURDKK","EURDKK!","EURDKK-T","EURDKKp","EURDKKm","EURDKKfw","EURDKK.raw","EURDKKm#","EURDKK.ffx","EURDKK.min","EURDKK="}; return(PickExisting(a)); }
   if(canonical=="EURGBP") { string a[]={"EURGBP","EURGBP.","EURGBP-T","EURGBP.p","EURGBP.fx","EURGBP.s","EURGBP.ecn","EURGBP!","EURGBP.S","EURGBP.hg","EURGBP...","EURGBP.sb","EURGBPp","EURGBP.c","EURGBPpro","EURGBP.esw","EURGBPm","EURGBPf","EURGBP.e","EURGBP.raw","EURGBP-","EURGBP.x","EURGBPx","EURGBP.iux","EURGBP.ffx","EURGBP.MRC","EURGBP..","EURGBP_SG","EURGBP.min","EURGBP=","EURGBP.sg","EURGBP.1","EURGBP.n","EURGBPi","EURGBPv","EURGBP.z"}; return(PickExisting(a)); }
   if(canonical=="EURHKD") { string a[]={"EURHKD","EURHKD.p","EURHKD!","EURHKD.fx","EURHKD-T","EURHKDp","EURHKD.","EURHKDm","EURHKD.ffx","EURHKD.min","EURHKD=","EURHKDi"}; return(PickExisting(a)); }
   if(canonical=="EURHUF") { string a[]={"EURHUF","EURHUF-T","EURHUFm","EURHUF.p","EURHUF.fx","EURHUF.pxm","EURHUF.sb","EURHUFp","EURHUFpro","EURHUFf","EURHUF.raw","EURHUF+","EURHUFmicro","EURHUF.ffx","EURHUF.min","EURHUFv"}; return(PickExisting(a)); }
   if(canonical=="EURJPY") { string a[]={"EURJPY","EURJPY!","EURJPY-T","EURJPY.","EURJPY.fx","EURJPY.s","EURJPY.ecn","EURJPY.S","EURJPY.ap","EURJPY...","EURJPY.sb","EURJPYp","EURJPY.c","EURJPYpro","EURJPY.esw","EURJPY#","EURJPYm","EURJPYv","EURJPYf","EURJPY.e","EURJPY.raw","EURJPY-","EURJPYmicro","EURJPYx","EURJPY.iux","EURJPY.ffx","EURJPY.MRC","EURJPY..","EURJPY_SG","EURJPY.min","EURJPY=","EURJPY.sg","EURJPYMic","EURJPY.1","EURJPY.t","EURJPYi","EURJPY.z"}; return(PickExisting(a)); }
   if(canonical=="EURMXN") { string a[]={"EURMXN","EURMXNm","EURMXN!","EURMXN.fx","EURMXN-T","EURMXN.hg","EURMXN.sb","EURMXNp","EURMXN.","EURMXN.raw","EURMXN+","EURMXN.x","EURMXN.p","EURMXN.ffx","EURMXN.ecn","EURMXN.."}; return(PickExisting(a)); }
   if(canonical=="EURNOK") { string a[]={"EURNOK","EURNOKm","EURNOK-T","EURNOK.","EURNOK!","EURNOK.fx","EURNOK.a","EURNOK...","EURNOK.sb","EURNOKp","EURNOKpro","EURNOK.raw","EURNOK+","EURNOKm#","EURNOK.ffx","EURNOK.ecn","EURNOK..","EURNOK.min","EURNOK=","EURNOK.d","EURNOK.c","EURNOKi"}; return(PickExisting(a)); }
   if(canonical=="EURNZD") { string a[]={"EURNZD","EURNZD.","EURNZDm","EURNZD!","EURNZD-T","EURNZD.fx","EURNZD.s","EURNZD.ecn","EURNZD.S","EURNZD.ap","EURNZD...","EURNZD.sb","EURNZDp","EURNZD.c","EURNZDpro","EURNZD.esw","EURNZDf","EURNZD.e","EURNZD.raw","EURNZD+","EURNZD-","EURNZD.p","EURNZD.lp","EURNZDx","EURNZD.iux","EURNZD.ffx","EURNZD.MRC","EURNZD..","EURNZD_SG","EURNZD.min","EURNZD=","EURNZDMic","EURNZDi","EURNZD.z"}; return(PickExisting(a)); }
   if(canonical=="EURPLN") { string a[]={"EURPLN","EURPLN.p","EURPLN-T","EURPLNm","EURPLN!","EURPLN.fx","EURPLN.sb","EURPLNp","EURPLNpro","EURPLN#","EURPLNv","EURPLN.raw","EURPLN+","EURPLN.","EURPLNmicro","EURPLN.ffx","EURPLN.min","EURPLNi"}; return(PickExisting(a)); }
   if(canonical=="EURSEK") { string a[]={"EURSEK","EURSEKm","EURSEK-T","EURSEK!","EURSEK.fx","EURSEK.vip","EURSEK.sb","EURSEKp","EURSEKpro","EURSEKf","EURSEK.raw","EURSEK+","EURSEK.","EURSEKmicro","EURSEK.ffx","EURSEK.ecn","EURSEK..","EURSEK.min","EURSEK=","EURSEK.d","EURSEK.n","EURSEKi"}; return(PickExisting(a)); }
   if(canonical=="EURSGD") { string a[]={"EURSGD","EURSGD.","EURSGDm","EURSGD!","EURSGD.fx","EURSGD-T","EURSGD.pxm","EURSGD.sb","EURSGD.m","EURSGD.c","EURSGD.raw","EURSGD.p","EURSGDm#","EURSGD.ffx","EURSGD..","EURSGD.min","EURSGD=","EURSGD.n","EURSGDi","EURSGDv"}; return(PickExisting(a)); }
   if(canonical=="EURTRY") { string a[]={"EURTRY","EURTRY!","EURTRY.","EURTRY.fx","EURTRY.a","EURTRY.sb","EURTRYp","EURTRYpro","EURTRYm","EURTRYv","EURTRY+","EURTRY.lp","EURTRY.ffx","EURTRY.min","EURTRY=","EURTRY.c","EURTRYi","EURTRY.p"}; return(PickExisting(a)); }
   if(canonical=="EURUSD") { string a[]={"EURUSD","EURUSDm","EURUSD.fx","EURUSD-T","EURUSD.qm","EURUSD.sb","EURUSD#","EURUSDpro","EURUSD.esw","EURUSDf","EURUSD.e","EURUSD.raw","EURUSD.c","EURUSD-","EURUSD.nnm","EURUSD.iux","EURUSD.s","EURUSD.","EURUSD.ffx","EURUSD.MRC","EURUSD..","EURUSD_SG","EURUSD.sg","EURUSD!","EURUSDMic","EURUSD.1","EURUSD.ecn","EURUSD.t","EURUSDi"}; return(PickExisting(a)); }
   if(canonical=="EURZAR") { string a[]={"EURZAR","EURZARm","EURZAR.fx","EURZAR-T","EURZAR.hg","EURZAR.sb","EURZARp","EURZAR.raw","EURZAR+","EURZAR.","EURZAR.ffx","EURZAR.min","EURZAR=","EURZAR!","EURZARc","EURZARi","EURZAR.s"}; return(PickExisting(a)); }
   if(canonical=="FTSE100") { string a[]={"UK100","FTSE100","FTSE","UK100Cash",".UK100",".UK100Cash","UK.100","[UK100]-T","UK100U6","UK100c","#FTSE100","#UK100","UK100.","#FTSE","UK100+","UK100.S","UK100.a","#GB100H_","UK100.CASH","UK100_SPOT","UK100p","UK100.E","$UK100","UK100.c.","UK100.m","UK.100+","UK100_m","FTSE100.p","UK100x","GB100","UK100.U6","UK100.s","UK100CASH","UK100spot","UK100.f","FTSE100=","UK100.c","UK100.U26",".UK100."}; return(PickExisting(a)); }
   if(canonical=="GBPAUD") { string a[]={"GBPAUD","GBPAUD.","GBPAUD!","GBPAUD-T","GBPAUDm","GBPAUD.p","GBPAUD.fx","GBPAUD.s","GBPAUD.ecn","GBPAUD.S","GBPAUD.ap","GBPAUD...","GBPAUD.sb","GBPAUDp","GBPAUD.c","GBPAUDpro","GBPAUD.esw","GBPAUDf","GBPAUD.e","GBPAUD.raw","GBPAUD+","GBPAUD-","GBPAUD.lp","GBPAUDx","GBPAUD.iux","GBPAUD.MRC","GBPAUD..","GBPAUD_SG","GBPAUD.min","GBPAUD=","GBPAUDMic","GBPAUD.1","GBPAUDi","GBPAUD.z"}; return(PickExisting(a)); }
   if(canonical=="GBPCAD") { string a[]={"GBPCAD","GBPCAD!","GBPCAD.","GBPCAD-T","GBPCADm","GBPCAD.p","GBPCAD.fx","GBPCAD.s","GBPCAD.ecn","GBPCAD.S","GBPCAD.hg","GBPCAD...","GBPCAD.sb","GBPCADp","GBPCAD.c","GBPCADpro","GBPCADf","GBPCAD.e","GBPCAD.raw","GBPCAD+","GBPCAD-","GBPCAD.lp","GBPCADx","GBPCAD.iux","GBPCAD.MRC","GBPCAD..","GBPCAD_SG","GBPCAD.min","GBPCAD=","GBPCADMic","GBPCAD.t","GBPCADi","GBPCAD.z"}; return(PickExisting(a)); }
   if(canonical=="GBPCHF") { string a[]={"GBPCHF","GBPCHF.","GBPCHF!","GBPCHF-T","GBPCHF.c","GBPCHFm","GBPCHF.p","GBPCHF.fx","GBPCHF.s","GBPCHF.ecn","GBPCHF.S","GBPCHF.pro","GBPCHF...","GBPCHF.sb","GBPCHFp","GBPCHFpro","GBPCHF.esw","GBPCHFf","GBPCHF.e","GBPCHF.raw","GBPCHF+","GBPCHF-","GBPCHFx","GBPCHF.iux","GBPCHF.MRC","GBPCHF..","GBPCHF_SG","GBPCHF.min","GBPCHF=","GBPCHF.1","GBPCHFi","GBPCHF.z"}; return(PickExisting(a)); }
   if(canonical=="GBPDKK") { string a[]={"GBPDKK","GBPDKK.fx","GBPDKK-T","GBPDKK.","GBPDKKm","GBPDKK.raw","GBPDKK.ffx","GBPDKK=","GBPDKK.p"}; return(PickExisting(a)); }
   if(canonical=="GBPJPY") { string a[]={"GBPJPY","GBPJPY.p","GBPJPY!","GBPJPY-T","GBPJPY.","GBPJPY.fx","GBPJPY.s","GBPJPY.ecn","GBPJPY.S","GBPJPY.a","GBPJPY...","GBPJPY.sb","GBPJPYp","GBPJPY.c","GBPJPYpro","GBPJPY.esw","GBPJPY#","GBPJPYm","GBPJPYf","GBPJPY.e","GBPJPY.raw","GBPJPY+","GBPJPY-","GBPJPYmicro","GBPJPYx","GBPJPY.iux","GBPJPY.ffx","GBPJPY.MRC","GBPJPY..","GBPJPY_SG","GBPJPY.min","GBPJPY=","GBPJPY.sg","GBPJPYMic","GBPJPY.1","GBPJPY.n","GBPJPYi","GBPJPY.z"}; return(PickExisting(a)); }
   if(canonical=="GBPNOK") { string a[]={"GBPNOK","GBPNOKm","GBPNOK.fx","GBPNOK-T","GBPNOK.vip","GBPNOK.sb","GBPNOK!","GBPNOK.","GBPNOK.x","GBPNOK.p","GBPNOK.ffx","GBPNOK.min","GBPNOK=","GBPNOKi"}; return(PickExisting(a)); }
   if(canonical=="GBPNZD") { string a[]={"GBPNZD","GBPNZD!","GBPNZD.","GBPNZD-T","GBPNZD.c","GBPNZD.p","GBPNZD.fx","GBPNZD.s","GBPNZD.ecn","GBPNZD.S","GBPNZD.a","GBPNZD...","GBPNZD.sb","GBPNZD.corp","GBPNZDp","GBPNZDpro","GBPNZD.esw","GBPNZD#","GBPNZDm","GBPNZDf","GBPNZD.e","GBPNZD.raw","GBPNZD+","GBPNZD-","GBPNZD-f","GBPNZDx","GBPNZD.iux","GBPNZD.ffx","GBPNZD.MRC","GBPNZD..","GBPNZD_SG","GBPNZD.min","GBPNZD=","GBPNZDi","GBPNZDv","GBPNZD.z"}; return(PickExisting(a)); }
   if(canonical=="GBPPLN") { string a[]={"GBPPLN","GBPPLN-T","GBPPLNm","GBPPLN.fx","GBPPLN.sb","GBPPLN#","GBPPLN.raw","GBPPLN+","GBPPLN.ffx","GBPPLN.p"}; return(PickExisting(a)); }
   if(canonical=="GBPSEK") { string a[]={"GBPSEK","GBPSEKm","GBPSEK.fx","GBPSEKzero","GBPSEK-T","GBPSEK.pxm","GBPSEK.sb","GBPSEKp","GBPSEK#","GBPSEKv","GBPSEK!","GBPSEK.raw","GBPSEK.","GBPSEKm#","GBPSEK.ffx","GBPSEK.min","GBPSEK=","GBPSEK.p","GBPSEK.n"}; return(PickExisting(a)); }
   if(canonical=="GBPSGD") { string a[]={"GBPSGD","GBPSGD-T","GBPSGD.","GBPSGDm","GBPSGD.p","GBPSGD.fx","GBPSGD.pxm","GBPSGD.sb","GBPSGD.m","GBPSGDp","GBPSGD.c","GBPSGD!","GBPSGD.raw","GBPSGD-f","GBPSGD.ffx","GBPSGD.ecn","GBPSGD..","GBPSGD.min","GBPSGD=","GBPSGDi"}; return(PickExisting(a)); }
   if(canonical=="GBPTRY") { string a[]={"GBPTRY","GBPTRY.fx","GBPTRYm","GBPTRY.ffx","GBPTRY.min","GBPTRY="}; return(PickExisting(a)); }
   if(canonical=="GBPUSD") { string a[]={"GBPUSD","GBPUSD.c","GBPUSD.","GBPUSD.fx","GBPUSD-T","GBPUSD.sb","GBPUSDx","GBPUSDpro","GBPUSD.esw","GBPUSDm","GBPUSDv","GBPUSDf","GBPUSD.e","GBPUSD.raw","GBPUSD-","GBPUSDmicro","GBPUSD.iux","GBPUSD.s","GBPUSD.MRC","GBPUSD..","GBPUSD_SG","GBPUSD.sg","GBPUSD!","GBPUSD.1","GBPUSD.ecn","GBPUSDi","GBPUSD.p"}; return(PickExisting(a)); }
   if(canonical=="GBPZAR") { string a[]={"GBPZAR","GBPZARm","GBPZAR.fx","GBPZAR-T","GBPZAR.sb","GBPZAR+","GBPZAR.x","GBPZAR.ffx","GBPZAR.min"}; return(PickExisting(a)); }
   if(canonical=="HK50") { string a[]={"HK50","HSI","#HSI","HKG33","HK50Cash",".HK50",".HK50Cash","[HK50]-T","HK50.","HK50c","HK50.S","HK50.a","#HSIF_","HSI.cash","HK50.CASH","HK50.E","$HK50","HK50.f","HK50.c","HK50m","#HongKong50","HSI.p","HSI.N26","HSIC","HK50x","HK50.s","HK50CASH","HK50p","HK50.g","HK50.t","HK50+","HK50.Q26",".HK50.","HK50.r"}; return(PickExisting(a)); }
   if(canonical=="HKDJPY") { string a[]={"HKDJPY","HKDJPYm","HKDJPY.fx","HKDJPY.p","HKDJPY-T","HKDJPY!","HKDJPYi","HKDJPYv"}; return(PickExisting(a)); }
   if(canonical=="IBEX35") { string a[]={"ES35","ESP35","SPA35","IBEX35",".ESP35Cash","[SPA35]-T",".ES35","ESP35U6","Spain35Cash","SPA35c","#IBEX35","#Spain35","#SPAIN35","Esp35","SPA35.a","IBEX35.cash",".SPAIN35","IBEX35_SPOT","ESP35p","ES35.E","$ES35","ES35.c.","SPA.35+","IBEX_35","SPA35spot","SPA35.f","ESP35.","ES35.mt4","ES35+","ES35.c",".ES35."}; return(PickExisting(a)); }
   if(canonical=="JP225") { string a[]={"JP225","JPN225","JP225Cash",".JPN225Cash","[JP225]-T",".JP225","JPN225c","JP225.c","JP225.m","#NIKKEI","NIKKEI","#N225","Jp225","JPN225.a","Nikkei","JPN225.CASH",".JAPAN225","JPN225_SPOT","N225","JPN225p","JP225.E","JP225USD","$JP225","JP225m","#JP225_U26","NIKKEI.p",".JP225Cash","JP225.F","#Japan225","JP225x","JP225.U6","JPN225.s","JP225.U26","JP225.g","JP225.","JP225=","JPN225.c","JPN225ft+","JPN225+",".JP225."}; return(PickExisting(a)); }
   if(canonical=="LTCUSD") { string a[]={"LTCUSD","LTCUSDT","LTCUSD.","LTCUSD-T","LTCUSDm","LTCUSD#","LTCUSD.futu","LTCUSD=","LTCUSD.c"}; return(PickExisting(a)); }
   if(canonical=="NAS100") { string a[]={"NAS100","USTEC","US100",".USTECHCash","NDX","US100Cash","NDXUSD","US100-T","USTECH","NASDAQ_USD",".US100","USTECHc","#Nasdaq","#NDX","NASDAQ","NAS100U6","NAS100.r","NAS100+","NAS100.S","NAS100.a","#NAS100H_","NAS100.cash","Nasdaq","NDX100",".NAS100","NDXUSD#","US100_Spot","NAS100p","NDXm","$US100","USTEC.c","US.100+","NAS100.p","NAS100.z","NAS100.s","US100CASH@","NDX100.g","US100spot","US100m","US100.f","NAS100.","NDX100=","TECH100","USTEC.U26",".USTEC.","NASDAQ_Z"}; return(PickExisting(a)); }
   if(canonical=="NATGAS") { string a[]={"XNGUSD","NGAS","NATGAS","NG","NGAS-T","NG-C","NAT.GASCash","NatGas",".XNGUSD","NAT.GAS","#NG","NGas","NGAS.S","XNGUSD.p","#NGF_","NATURAL_GAS","NGAS.f","NGASp","$$NG","#NG.L","NATGAS+","NATGAS.s","Natural_Gas","XNGUSD.","NATGAS.","NGG","NGAS.p","NATGAS.f","NGS",".NGas"}; return(PickExisting(a)); }
   if(canonical=="NOKJPY") { string a[]={"NOKJPY","NOKJPY.fx","NOKJPY.vip","NOKJPY.sb","NOKJPY.m","NOKJPY-","NOKJPYm","NOKJPY!","NOKJPY.","NOKJPY.x","NOKJPY.p","NOKJPYv"}; return(PickExisting(a)); }
   if(canonical=="NOKSEK") { string a[]={"NOKSEK","NOKSEKm","NOKSEK.","NOKSEK.p","NOKSEKzero","NOKSEK-T","NOKSEK.pxm","NOKSEK.sb","NOKSEK.m","NOKSEKp","NOKSEK!","NOKSEK.x","NOKSEK.ffx","NOKSEK=","NOKSEK.edge"}; return(PickExisting(a)); }
   if(canonical=="NZDCAD") { string a[]={"NZDCAD","NZDCAD!","NZDCAD.s","NZDCAD-T","NZDCADm","NZDCAD.p","NZDCAD.","NZDCAD.fx","NZDCAD.ecn","NZDCAD.S","NZDCAD.vip","NZDCAD...","NZDCAD.sb","NZDCAD.corp","NZDCADp","NZDCAD.c","NZDCADpro","NZDCADf","NZDCAD.e","NZDCAD.raw","NZDCAD+","NZDCAD-","NZDCADx","NZDCAD.iux","NZDCAD.ffx","NZDCAD.MRC","NZDCAD..","NZDCAD.min","NZDCAD=","NZDCADMic","NZDCAD.n","NZDCADi","NZDCAD.z"}; return(PickExisting(a)); }
   if(canonical=="NZDCHF") { string a[]={"NZDCHF","NZDCHF.","NZDCHF!","NZDCHF-T","NZDCHF.p","NZDCHF.fx","NZDCHF.s","NZDCHF.ecn","NZDCHF.S","NZDCHF.a","NZDCHF...","NZDCHF.sb","NZDCHFp","NZDCHF.c","NZDCHFpro","NZDCHFm","NZDCHFf","NZDCHF.e","NZDCHF.raw","NZDCHF+","NZDCHF-","NZDCHFx","NZDCHF.iux","NZDCHF.ffx","NZDCHF.MRC","NZDCHF..","NZDCHF.min","NZDCHF=","NZDCHF.n","NZDCHFi","NZDCHF.z"}; return(PickExisting(a)); }
   if(canonical=="NZDJPY") { string a[]={"NZDJPY","NZDJPY!","NZDJPY-T","NZDJPY.c","NZDJPY.","NZDJPY.fx","NZDJPY.s","NZDJPY.ecn","NZDJPY.S","NZDJPY.pxm","NZDJPY...","NZDJPY.sb","NZDJPYp","NZDJPYpro","NZDJPY.esw","NZDJPY#","NZDJPYm","NZDJPYv","NZDJPYf","NZDJPY.e","NZDJPY.raw","NZDJPY+","NZDJPY-","NZDJPY.lp","NZDJPYx","NZDJPY.iux","NZDJPY.ffx","NZDJPY.MRC","NZDJPY..","NZDJPY_SG","NZDJPY.min","NZDJPY=","NZDJPY.1","NZDJPYi","NZDJPY.z"}; return(PickExisting(a)); }
   if(canonical=="NZDSGD") { string a[]={"NZDSGD","NZDSGD.p","NZDSGD-T","NZDSGD.fx","NZDSGD.sb","NZDSGDp","NZDSGD.c","NZDSGD.","NZDSGDm","NZDSGD!","NZDSGD.raw","NZDSGD.pro","NZDSGDmicro","NZDSGD.ffx","NZDSGD.min","NZDSGD="}; return(PickExisting(a)); }
   if(canonical=="NZDUSD") { string a[]={"NZDUSD","NZDUSD-T","NZDUSDm","NZDUSD.","NZDUSD.fx","NZDUSD.ecn","NZDUSD.vip","NZDUSD...","NZDUSD.sb","NZDUSDpro","NZDUSD.esw","NZDUSDv","NZDUSDf","NZDUSD.e","NZDUSD.raw","NZDUSD.c","NZDUSD-","NZDUSD.shh","NZDUSDx","NZDUSD.iux","NZDUSD.s","NZDUSD.ffx","NZDUSD.MRC","NZDUSD..","NZDUSD_SG","NZDUSD.min","NZDUSD=","NZDUSD.sg","NZDUSD!","NZDUSD.fix","NZDUSD.1","NZDUSD.t","NZDUSDi"}; return(PickExisting(a)); }
   if(canonical=="SEKJPY") { string a[]={"SEKJPY","SEKJPYm","SEKJPY.fx","SEKJPYzero","SEKJPY.ap","SEKJPY!","SEKJPY.","SEKJPY.x","SEKJPY.p","SEKJPYv"}; return(PickExisting(a)); }
   if(canonical=="SGDJPY") { string a[]={"SGDJPY","SGDJPYm","SGDJPY.p","SGDJPY-T","SGDJPY.a","SGDJPY.sb","SGDJPY.m","SGDJPY.c","SGDJPYpro","SGDJPY#","SGDJPY!","SGDJPY.","SGDJPYmicro","SGDJPY.iux","SGDJPY.ffx","SGDJPYi"}; return(PickExisting(a)); }
   if(canonical=="SP500") { string a[]={"US500","SPX500","SP500","SPXUSD","SPX",".US500Cash","S&P500","US500Cash","SPXm","_SP500","[USA500]-T","SP500_USD",".US500","US500U6","US500c","#SP500","#SPX","Usa500","SP500.S","#US500H_","SPX500.cash","US500.CASH",".SP500","SPXUSD#","US500_SPOT","SPX500p","US500.E","$US500","SP500.R","US.500+","SPX500_m","SP500.s","#US500_U26","S&P_500","SPX500.p","SP500.","#US500","US500x","US500.s","US500CASH","SPX500.g","USA500spot","SPX500m","US500.f","SPXC","SPX500.","SP500-JU26","SPX500="}; return(PickExisting(a)); }
   if(canonical=="STOXX50") { string a[]={"EU50","EUSTX50","STOXX50","STOXX50E",".STOXX50","EU50Cash","EURO50",".EURO50Cash","ESTX50","EU50c","STOXX50.c","#ESTX50","#Euro50","#STOXX50","Euro50","EUSTX50.a","#EU50H_","EUSTX50p","EU50.E","$EU50","STOXX50m","EU.50+","EU50Cash#","EU50x","EU50.U6","EU50spot","EU50.f","EUSTX50.","EU50=","EUSTX50.n","EU50+","EUSTX50+",".STOXX50."}; return(PickExisting(a)); }
   if(canonical=="US2000") { string a[]={"US2000","RUS2000","US2000.f","US2000+","US2000.m","RTYU26","RUS2000p","#US2000","US2000c",".US2000.","US2000.r"}; return(PickExisting(a)); }
   if(canonical=="US30") { string a[]={"US30","DJ30","WS30",".US30Cash","US30Cash",".US30","#DOW","DOW30","#DOW-T","DOW30_USD","US30U6","US30c","DJ30.U26","#Dow","_DJI","DJIUSD","USA.30","DJ30.S","US30.a","#US30H_","US30USD","DJIUSD-","DJ30.cash","US30.CASH","DJ30.f","DJIUSD#","US30_SPOT","US30p","US30.E","WS30m","DJ30.c.","US30m","DJ30.R","US.30+","#DJ30_U26","DOW.p","US30.F","WS30-f","#DOW30","US30x","DJI","DOWJ","US30.U6","US30.s","#DJ30","WS30.g","US30spot","US30.f"}; return(PickExisting(a)); }
   if(canonical=="USDCAD") { string a[]={"USDCAD","USDCAD.","USDCAD-T","USDCAD.fx","USDCAD.ecn","USDCAD.ap","USDCAD...","USDCAD.sb","USDCADpro","USDCAD.esw","USDCADm","USDCADf","USDCAD.e","USDCAD.raw","USDCAD.c","USDCAD-","USDCAD.p","USDCADm#","USDCADx","USDCAD.iux","USDCAD.s","USDCAD.ffx","USDCAD.MRC","USDCAD..","USDCAD_SG","USDCAD=","USDCAD.sg","USDCAD!","USDCAD.1","USDCAD.t","USDCADi","USDCADv"}; return(PickExisting(a)); }
   if(canonical=="USDCHF") { string a[]={"USDCHF","USDCHF.","USDCHF-T","USDCHF.a","USDCHFm","USDCHF.fx","USDCHF...","USDCHF.sb","USDCHFpro","USDCHF.esw","USDCHFf","USDCHF.e","USDCHF.raw","USDCHF.c","USDCHF-","USDCHF.p","USDCHF.fix","USDCHFx","USDCHF.iux","USDCHF.ffx","USDCHF.MRC","USDCHF..","USDCHF_SG","USDCHF.min","USDCHF=","USDCHF.sg","USDCHF!","USDCHFMic","USDCHF.1","USDCHF.ecn","USDCHFi","USDCHF.z"}; return(PickExisting(a)); }
   if(canonical=="USDCNH") { string a[]={"USDCNH","USDCNH-T","USDCNH.p","USDCNH!","USDCNH.c","USDCNH.","USDCNH.S","USDCNH.a","USDCNH.sb","USDCNHp","USDCNHpro","USDCNH#","USDCNHm","USDCNH.e","USDCNH.raw","USDCNH+","USDCNHm#","USDCNH.s","USDCNH.ffx","USDCNH.ecn","USDCNH..","USDCNH_SG","USDCNH.min","USDCNHMic"}; return(PickExisting(a)); }
   if(canonical=="USDCZK") { string a[]={"USDCZK","USDCZK-T","USDCZK.fx","USDCZK.p","USDCZK.hg","USDCZKp","USDCZK.","USDCZKm","USDCZKv","USDCZK.raw","USDCZK.z","USDCZK.ffx","USDCZK.min","USDCZK!"}; return(PickExisting(a)); }
   if(canonical=="USDDKK") { string a[]={"USDDKK","USDDKKm","USDDKK!","USDDKK.fx","USDDKK-T","USDDKK...","USDDKKp","USDDKKpro","USDDKK#","USDDKKfw","USDDKK.raw","USDDKK.ffx","USDDKK.min","USDDKK=","USDDKK.p","USDDKKi"}; return(PickExisting(a)); }
   if(canonical=="USDHKD") { string a[]={"USDHKD","USDHKD.c","USDHKD.fx","USDHKD-T","USDHKD.a","USDHKD.sb","USDHKDp","USDHKDpro","USDHKD#","USDHKDm","USDHKD.p","USDHKD.e","USDHKD.iux","USDHKD.ffx","USDHKD..","USDHKD_SG","USDHKD.min","USDHKDMic","USDHKDi"}; return(PickExisting(a)); }
   if(canonical=="USDHUF") { string a[]={"USDHUF","USDHUFm","USDHUF.fx","USDHUF-T","USDHUF.pxm","USDHUF.sb","USDHUFp","USDHUFpro","USDHUF.raw","USDHUFmicro","USDHUF.ffx","USDHUF.min","USDHUF.p","USDHUF!"}; return(PickExisting(a)); }
   if(canonical=="USDILS") { string a[]={"USDILS","USDILSm","USDILS.b"}; return(PickExisting(a)); }
   if(canonical=="USDJPY") { string a[]={"USDJPY","USDJPY.","USDJPYv","USDJPY.c","USDJPY.fx","USDJPY-T","USDJPY.ax","USDJPY...","USDJPY.sb","USDJPY.P","USDJPYpro","USDJPY.esw","USDJPYm","USDJPYf","USDJPY.e","USDJPY.raw","USDJPY-","USDJPY.p","USDJPY.v","USDJPY.iux","USDJPY.s","USDJPY.MRC","USDJPY..","USDJPY_SG","USDJPY.sg","USDJPY!","USDJPYMic","USDJPY.1","USDJPY.ecn","USDJPYi"}; return(PickExisting(a)); }
   if(canonical=="USDMXN") { string a[]={"USDMXN","USDMXNm","USDMXN!","USDMXN.fx","USDMXN-T","USDMXN...","USDMXN.sb","USDMXNp","USDMXNpro","USDMXN.raw","USDMXN+","USDMXN.","USDMXNm#","USDMXN.ffx","USDMXN.ecn","USDMXN..","USDMXN.min","USDMXN=","USDMXN.d","USDMXN.n","USDMXNi"}; return(PickExisting(a)); }
   if(canonical=="USDNOK") { string a[]={"USDNOK","USDNOKm","USDNOK!","USDNOK.fx","USDNOK-T","USDNOK.pxm","USDNOK...","USDNOK.sb","USDNOKp","USDNOKpro","USDNOK#","USDNOKv","USDNOKf","USDNOK.e","USDNOK.raw","USDNOK+","USDNOK.","USDNOK.ffx","USDNOK.ecn","USDNOK..","USDNOK.min","USDNOK=","USDNOK.d","USDNOKi"}; return(PickExisting(a)); }
   if(canonical=="USDPLN") { string a[]={"USDPLN","USDPLNm","USDPLN-T","USDPLN.p","USDPLN.fx","USDPLN.pxm","USDPLN.sb","USDPLNp","USDPLNpro","USDPLN#","USDPLN.raw","USDPLN.","USDPLN.x","USDPLN.ffx","USDPLN.min","USDPLN.d","USDPLN!","USDPLNi"}; return(PickExisting(a)); }
   if(canonical=="USDRUB") { string a[]={"USDRUB","USDRUB-T","USDRUBm","USDRUB.fx","USDRUBzero","USDRUBpro","USDRUB!","USDRUB.lp","USDRUB.min","USDRUB_Ask","USDRUB.d"}; return(PickExisting(a)); }
   if(canonical=="USDSEK") { string a[]={"USDSEK","USDSEKm","USDSEK!","USDSEK.fx","USDSEK-T","USDSEK.pxm","USDSEK.sb","USDSEKp","USDSEKpro","USDSEKf","USDSEK.e","USDSEK.raw","USDSEK+","USDSEK.","USDSEK.z","USDSEK.ffx","USDSEK.ecn","USDSEK..","USDSEK.min","USDSEK=","USDSEK.d","USDSEKi","USDSEKv"}; return(PickExisting(a)); }
   if(canonical=="USDSGD") { string a[]={"USDSGD","USDSGD.","USDSGDm","USDSGD!","USDSGD.fx","USDSGD-T","USDSGD.ap","USDSGD.sb","USDSGDp","USDSGD.c","USDSGDpro","USDSGD.esw","USDSGD.e","USDSGD.raw","USDSGDm#","USDSGD.iux","USDSGD.ffx","USDSGD.ecn","USDSGD..","USDSGD.min","USDSGD=","USDSGD.conv","USDSGD.t","USDSGDi","USDSGD.s"}; return(PickExisting(a)); }
   if(canonical=="USDTHB") { string a[]={"USDTHB","USDTHBzero","USDTHB-T","USDTHB.pxm","USDTHBm","USDTHB.raw","USDTHB-","USDTHB.","USDTHB#","USDTHB.iux","USDTHB.s","USDTHBs."}; return(PickExisting(a)); }
   if(canonical=="USDTRY") { string a[]={"USDTRY","USDTRYv","USDTRY!","USDTRY.","USDTRY.fx","USDTRY-T","USDTRY.vip","USDTRY.sb","USDTRYp","USDTRYpro","USDTRYm","USDTRYm#","USDTRY.ffx","USDTRY.min","USDTRY=","USDTRYi","USDTRY.s"}; return(PickExisting(a)); }
   if(canonical=="USDZAR") { string a[]={"USDZAR","USDZARm","USDZAR!","USDZAR.fx","USDZAR-T","USDZAR.p","USDZAR...","USDZAR.sb","USDZARp","USDZARpro","USDZAR#","USDZARfw","USDZAR.raw","USDZAR+","USDZAR.","USDZARmicro","USDZAR.ffx","USDZAR.ecn","USDZAR..","USDZAR.min","USDZAR=","USDZAR.d","USDZAR.c","USDZARi","USDZARv","USDZAR.s"}; return(PickExisting(a)); }
   if(canonical=="WTI") { string a[]={"XTIUSD","USOIL","WTI","USOil","#CL","OILUSD","CL","#USO","USOIL.c","CL.N","CRUDEOIL","US.OIL-T",".USOil","WTICash","XTIUSD.c","XTIUSD.",".XTIUSD","CLX","XTIUSD.s","USOilSpot","USOIL.S","USOIL.a","#USOILF_","USOIL.CASH","USO","USOIL-","XTIUSD.lmx","USOilp","$WTI","USOil.m","CL.R","Crude_Oil","#CLX","USOIL.","OILUS","WTI.f","CLI","XTIUSD=","USOil-","WTIF!",".CLR","USOIL+","USOilCash","XTIUSD.z"}; return(PickExisting(a)); }
   if(canonical=="XAGEUR") { string a[]={"XAGEUR","XAGEUR.p","SILVEREURO","XAGEURpro","XAGEURm","XAGEUR.raw","XAGEUR.x","XAGEUR.iux","XAGEUR.z"}; return(PickExisting(a)); }
   if(canonical=="XAGUSD") { string a[]={"XAGUSD","SILVER","XAGUSD.p","XAGUSD.s","XAGUSD.","SILVER-T","SILVER_USD","SILVER.f","XAGUSDx","SILVER.m","XAGUSD!","XAGUSD.S","XAGUSDpm","Silver.sb","Silver#","XAG_USD","SILVERUSD","XAGUSD.m","XAGUSDp","XAGUSD.c","XAGUSDpro","XAGUSDm","SILVER.03","XAGUSD#","XAGUSDf","XAGUSD.e","XAGUSD.raw","SILVERs+","XAGUSDM","Silver","SILVERX","XAGUSDmini.z","XAGUSD.std","XAGUSD.iux","XAGUSD.ffx","XAGUSD.MRC","XAGUSD..","XAGUSD_SG","XAGUSD=","SILVER.S","XAGUSD.ecn","XAGUSD.n","XAGUSDi","XAGUSD.z"}; return(PickExisting(a)); }
   if(canonical=="XAUEUR") { string a[]={"XAUEUR","XAUEUR.p","GOLDEURO","XAUEUR-T","GOLD/EUR","XAU_EUR","XAUEURp","XAUEURpro","XAUEUR.","XAUEURm","GOLDEUR","XAUEUR.raw","XAUEUR.x","XAUEUR.iux","XAUEUR.ecn","XAUEUR..","XAUEUR=","XAUEUR!","XAUEUR.z"}; return(PickExisting(a)); }
   if(canonical=="XAUUSD") { string a[]={"XAUUSD","GOLD","XAUUSD.s","XAUUSD.","GOLD-T","GOLD_USD","GOLD.f","XAUUSDx","XAUUSDm","XAUUSD.p","GOLD.m","XAUUSD.ecn","XAUUSD!","XAUUSD.S","XAUUSDpm","GOLDsb","Gold#","XAU_USD","GOLDUSD","XAUUSD247p","XAUUSDpro","GOLD.12","XAUUSD#","XAUUSDf","XAUUSD.e","XAUUSD.raw","GOLDs+","Gold","GOLDX","XAUUSDTTBAR.s","XAUUSD.std","XAUUSD.iux","XAUUSD.ffx","XAUUSD.MRC","XAUUSD..","XAUUSD_SG","XAUUSD=","GOLD.S","XAUUSDMic","XAUUSD.1","XAUUSD.c","XAUUSDi","XAUUSD.z"}; return(PickExisting(a)); }
   if(canonical=="XPDUSD") { string a[]={"XPDUSD","PALLADIUM","Palladium","XPDUSD.m","XPDUSD.p","XPDUSD.S","XPDUSD.pxm","XPD_USD","XPDUSDp","XPDUSDpro","XPDUSDm","XPDUSD#","PALLADIUM+","XPDUSD.s","XPDUSD.iux","XPDUSD.g","XPDUSD.ffx","PALLADIUM.f","XPDUSD.ecn","XPDUSD..","XPDUSD.","XPDUSD=","XPDUSD!","XPDUSDi","XPDUSD.r","XPDUSD.z"}; return(PickExisting(a)); }
   if(canonical=="XPTUSD") { string a[]={"XPTUSD","PLATINUM","Platinum","XPTUSD.mq","XPTUSD.p","XPTUSD.S","XPTUSD.hg","XPT_USD","XPTUSDp","XPTUSDx","XPTUSDpro","XPTUSDm","XPTUSD#","PLATINUM+","XPTUSD.pro","XPTUSD-f","XPTUSD.iux","XPTUSD.ffx","PLATINUM.f","XPTUSD.ecn","XPTUSD..","XPTUSD.","XPTUSD=","XPTUSD''","XPTUSD!","XPTUSDi","XPTUSD.r","XPTUSD.z"}; return(PickExisting(a)); }
   if(canonical=="XRPUSD") { string a[]={"XRPUSD","XRPUSDT","XRPUSD.","XRPUSD-T","XRPUSD#","XRPUSDm","XRPUSD.futu","XRPUSD=","XRPUSD.c"}; return(PickExisting(a)); }
   if(canonical=="ZARJPY") { string a[]={"ZARJPY","ZARJPY.p","ZARJPY.fx","ZARJPY.pxm","ZARJPYpro","ZARJPY#","ZARJPYm","ZARJPYfw","ZARJPY."}; return(PickExisting(a)); }
   return(ScanTerminal(canonical));
}

// Clamp a desired volume to the broker's min/max and snap it to its step.
// Skipping this is the usual cause of error 131 (invalid trade volume).
double NormalizeLots(string canonical,double desired)
{
   string s=ResolveSymbol(canonical);
   if(s=="") return(0.0);
   double mn=SymbolInfoDouble(s,SYMBOL_VOLUME_MIN), st=SymbolInfoDouble(s,SYMBOL_VOLUME_STEP), mx=SymbolInfoDouble(s,SYMBOL_VOLUME_MAX);
   if(st<=0.0) st=0.01;
   double v=MathFloor(desired/st+0.0000001)*st;
   if(v<mn) v=mn;
   if(mx>0.0 && v>mx) v=mx;
   return(NormalizeDouble(v,2));
}
